#!/usr/bin/env -S node --experimental-strip-types
import { pathToFileURL } from 'node:url';

type JsonObject = Record<string, any>;

export interface HostedPlannerSmokeResult {
  ok: true;
  baseUrl: string;
  planId: string;
  runId: string;
  version: unknown;
  eventCount: number;
  sseEventCount: number;
  archived: boolean;
}

interface HostedPlannerSmokeOptions {
  baseUrl?: string;
  apiToken?: string;
  timeoutMs?: number;
}

export async function runHostedPlannerSmoke(options: HostedPlannerSmokeOptions = {}): Promise<HostedPlannerSmokeResult> {
  const baseUrl = (options.baseUrl || process.env.OD_HOSTED_BASE_URL || 'https://open-design.ignitabull.org').replace(/\/$/, '');
  const apiToken = (options.apiToken || process.env.OD_API_TOKEN || '').trim();
  const timeoutMs = options.timeoutMs ?? Number(process.env.OD_HOSTED_SMOKE_TIMEOUT_MS || 45_000);
  if (!apiToken) {
    throw Object.assign(
      new Error('OD_API_TOKEN is required. Export the hosted daemon token before running this smoke.'),
      { exitCode: 2 },
    );
  }

  function url(path: string): string {
    return `${baseUrl}${path.startsWith('/') ? path : `/${path}`}`;
  }

  async function request(path: string, init: RequestInit = {}): Promise<JsonObject> {
    const response = await fetchWithTimeout(url(path), {
      ...init,
      headers: {
        authorization: `Bearer ${apiToken}`,
        'content-type': 'application/json',
        ...(init.headers ?? {}),
      },
    }, timeoutMs);
    const body = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(`${init.method ?? 'GET'} ${path} failed with ${response.status}: ${JSON.stringify(body)}`);
    }
    return body as JsonObject;
  }

  const health = await request('/api/health');
  if (health.ok !== true) throw new Error('health check did not return ok=true');

  const unauthenticated = await fetchWithTimeout(url('/api/plans'), {}, timeoutMs);
  if (unauthenticated.status !== 401) {
    throw new Error(`protected API check expected 401 without token, got ${unauthenticated.status}`);
  }

  const session = await fetchWithTimeout(url('/api/planning/session'), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ token: apiToken }),
  }, timeoutMs);
  if (!session.ok || !session.headers.get('set-cookie')?.includes('od_planning_session=')) {
    throw new Error(`planning session cookie check failed with ${session.status}`);
  }

  const stamp = new Date().toISOString();
  const created = await request('/api/plans', {
    method: 'POST',
    body: JSON.stringify({
      name: `Hosted smoke ${stamp}`,
      intent: {
        purpose: 'Verify hosted Open Design planner persistence, auth, and section-agent events.',
        audience: 'Open Design operators',
        constraints: ['single-tenant hosted daemon', 'Cloudflare-fronted public origin'],
        successCriteria: ['protected API', 'persisted plan', 'section-agent run events'],
      },
      selectedTools: [
        { toolId: 'github', status: 'wanted' },
        { toolId: 'cloudflare-hosting', status: 'wanted' },
        { toolId: 'codex', status: 'wanted' },
      ],
      stack: {
        frontend: 'next',
        backend: 'hono',
        runtime: 'workers',
        database: 'supabase',
        auth: 'better-auth',
        hosting: ['cloudflare'],
      },
    }),
  });
  const planId = created.plan?.id;
  if (!planId) throw new Error('create plan response did not include plan.id');

  await request(`/api/plans/${encodeURIComponent(planId)}/sections/planning`, {
    method: 'PATCH',
    body: JSON.stringify({
      status: 'answered',
      answers: ['Hosted smoke can create and edit section answers through the protected API.'],
      notes: 'Generated by deploy/scripts/smoke-hosted-planner.ts',
    }),
  });

  await request(`/api/plans/${encodeURIComponent(planId)}`, {
    method: 'PATCH',
    body: JSON.stringify({
      selectedTools: [
        { toolId: 'github', status: 'wanted' },
        { toolId: 'cloudflare-hosting', status: 'connected', notes: 'Hosted smoke confirmed public daemon routing.' },
        { toolId: 'codex', status: 'wanted' },
      ],
      stack: {
        frontend: 'next',
        backend: 'hono',
        runtime: 'node',
        database: 'sqlite',
        auth: 'better-auth',
        hosting: ['cloudflare'],
      },
    }),
  });

  const runResult = await request(`/api/plans/${encodeURIComponent(planId)}/sections/planning/runs`, {
    method: 'POST',
    body: '{}',
  });
  const runId = runResult.run?.id;
  if (!runId) throw new Error('section run response did not include run.id');

  const runEvents = await request(`/api/plans/${encodeURIComponent(planId)}/sections/runs/${encodeURIComponent(runId)}/events`);
  if (!Array.isArray(runEvents.events) || runEvents.events.length === 0) {
    throw new Error('section run event replay returned no events');
  }
  const sseEvents = await readRunEventStream(url(`/api/plans/${encodeURIComponent(planId)}/sections/runs/${encodeURIComponent(runId)}/events`), apiToken);
  if (sseEvents.length === 0) {
    throw new Error('section run SSE stream returned no events');
  }

  const reloaded = await request(`/api/plans/${encodeURIComponent(planId)}`);
  const answer = reloaded.plan?.sectionAnswers?.planning;
  if (!answer?.answers?.some((item: string) => item.includes('Hosted smoke'))) {
    throw new Error('reloaded plan did not preserve the planning section answer');
  }
  if (!reloaded.plan?.executionRuns?.some((run: JsonObject) => run.id === runId)) {
    throw new Error('reloaded plan did not preserve the section-agent run');
  }

  await request(`/api/plans/${encodeURIComponent(planId)}/archive`, {
    method: 'POST',
    body: JSON.stringify({
      archived: true,
      reason: 'Hosted smoke completed successfully.',
    }),
  });

  return {
    ok: true,
    baseUrl,
    planId,
    runId,
    version: health.version,
    eventCount: runEvents.events.length,
    sseEventCount: sseEvents.length,
    archived: true,
  };
}

async function readRunEventStream(streamUrl: string, apiToken: string): Promise<JsonObject[]> {
  const response = await fetchWithTimeout(streamUrl, {
    headers: {
      accept: 'text/event-stream',
      authorization: `Bearer ${apiToken}`,
    },
  }, Number(process.env.OD_HOSTED_SMOKE_SSE_TIMEOUT_MS || 45_000));
  if (!response.ok || !response.body) {
    throw new Error(`section run SSE stream failed with ${response.status}`);
  }
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  const events: JsonObject[] = [];
  let buffer = '';
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const blocks = buffer.split('\n\n');
    buffer = blocks.pop() ?? '';
    for (const block of blocks) {
      const lines = block.split('\n');
      const eventName = lines.find((line) => line.startsWith('event: '))?.slice('event: '.length);
      const dataRaw = lines.find((line) => line.startsWith('data: '))?.slice('data: '.length);
      if (eventName === 'done') return events;
      if (!dataRaw || block.startsWith(':')) continue;
      const data = JSON.parse(dataRaw) as JsonObject;
      events.push(data);
    }
  }
  return events;
}

async function fetchWithTimeout(url: string, init: RequestInit, timeoutMs: number): Promise<Response> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timeout);
  }
}

async function main() {
  const result = await runHostedPlannerSmoke();
  console.log(JSON.stringify(result, null, 2));
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().then(() => {
    process.exit(0);
  }).catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(typeof error?.exitCode === 'number' ? error.exitCode : 1);
  });
}
